[package]
name = "rust"
version = "0.1.0"
authors = []

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { git = 'https://github.com/alexcrichton/wasm-bindgen' }

[profile.dev]
opt-level = 's'
panic = 'abort'

# to see the release binary in development (for size reasons mostly) uncomment
# these lines
debug = false
overflow-checks = false
debug-assertions = false

[profile.release]
opt-level = 's'
panic = 'abort'
